"""add_pgvector_extension_and_vector_columns

Revision ID: 206ad674720a
Revises: f10c765e40a2
Create Date: 2025-01-27 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '206ad674720a'
down_revision: Union[str, None] = 'f10c765e40a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing columns that the application expects
    try:
        op.add_column('chat_messages', sa.Column('message_type', sa.String(50), nullable=True))
        print("✅ Added message_type column")
    except Exception as e:
        print(f"ℹ️ message_type column already exists or failed: {e}")
    
    try:
        op.add_column('chat_messages', sa.Column('embedding_vector', sa.Text(), nullable=True))
        print("✅ Added embedding_vector column (Text fallback)")
    except Exception as e:
        print(f"ℹ️ embedding_vector column already exists or failed: {e}")
    
    # Create indexes for better query performance
    try:
        op.create_index('ix_chat_messages_message_type', 'chat_messages', ['message_type'])
        print("✅ Created message_type index")
    except Exception as e:
        print(f"ℹ️ message_type index already exists or failed: {e}")
    
    try:
        op.create_index('ix_chat_messages_timestamp_desc', 'chat_messages', ['timestamp'], postgresql_ops={'timestamp': 'DESC'})
        print("✅ Created timestamp index")
    except Exception as e:
        print(f"ℹ️ timestamp index already exists or failed: {e}")
    
    print("🎉 Vector database migration completed successfully!")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove indexes
    try:
        op.drop_index('ix_chat_messages_timestamp_desc', table_name='chat_messages')
    except:
        pass
    
    try:
        op.drop_index('ix_chat_messages_message_type', table_name='chat_messages')
    except:
        pass
    
    # Remove columns
    try:
        op.drop_column('chat_messages', 'embedding_vector')
    except:
        pass
    
    try:
        op.drop_column('chat_messages', 'message_type')
    except:
        pass
    
    # ### end Alembic commands ###
