"""add_user_customization_fields

Revision ID: ea816b0cc0b9
Revises: 750939ba8628
Create Date: 2025-07-28 14:26:32.941440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea816b0cc0b9'
down_revision: Union[str, None] = '750939ba8628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_plans_assessment_id', table_name='daily_plans')
    op.drop_index('ix_daily_plans_id', table_name='daily_plans')
    op.drop_index('ix_daily_plans_user_id', table_name='daily_plans')
    op.drop_table('daily_plans')
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_message_type', table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_timestamp_desc', table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_user_assessments_id', table_name='user_assessments')
    op.drop_index('ix_user_assessments_user_id', table_name='user_assessments')
    op.drop_table('user_assessments')
    op.drop_index('ix_progress_snapshots_assessment_id', table_name='progress_snapshots')
    op.drop_index('ix_progress_snapshots_id', table_name='progress_snapshots')
    op.drop_index('ix_progress_snapshots_user_id', table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index('ix_user_preferences_id', table_name='user_preferences')
    op.drop_index('ix_user_preferences_user_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('ix_habit_feedback_id', table_name='habit_feedback')
    op.drop_index('ix_habit_feedback_user_id', table_name='habit_feedback')
    op.drop_table('habit_feedback')
    op.drop_index('ix_plan_customizations_id', table_name='plan_customizations')
    op.drop_index('ix_plan_customizations_user_id', table_name='plan_customizations')
    op.drop_table('plan_customizations')
    op.drop_index('ix_future_projections_assessment_id', table_name='future_projections')
    op.drop_index('ix_future_projections_id', table_name='future_projections')
    op.drop_index('ix_future_projections_user_id', table_name='future_projections')
    op.drop_table('future_projections')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_habit_completions_assessment_id', table_name='habit_completions')
    op.drop_index('ix_habit_completions_daily_plan_id', table_name='habit_completions')
    op.drop_index('ix_habit_completions_id', table_name='habit_completions')
    op.drop_index('ix_habit_completions_user_id', table_name='habit_completions')
    op.drop_table('habit_completions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_completions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('habit_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('habit_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('day_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['user_assessments.id'], name='habit_completions_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plans.id'], name='habit_completions_daily_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='habit_completions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='habit_completions_pkey')
    )
    op.create_index('ix_habit_completions_user_id', 'habit_completions', ['user_id'], unique=False)
    op.create_index('ix_habit_completions_id', 'habit_completions', ['id'], unique=False)
    op.create_index('ix_habit_completions_daily_plan_id', 'habit_completions', ['daily_plan_id'], unique=False)
    op.create_index('ix_habit_completions_assessment_id', 'habit_completions', ['assessment_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('future_projections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('orchestrator_output', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('quiz_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('photo_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('projection_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('weekly_plan', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['user_assessments.id'], name='future_projections_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='future_projections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='future_projections_pkey')
    )
    op.create_index('ix_future_projections_user_id', 'future_projections', ['user_id'], unique=False)
    op.create_index('ix_future_projections_id', 'future_projections', ['id'], unique=False)
    op.create_index('ix_future_projections_assessment_id', 'future_projections', ['assessment_id'], unique=False)
    op.create_table('plan_customizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('preferred_wake_up_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('preferred_bedtime', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('exercise_intensity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('preferred_exercise_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('energy_peak_hours', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('stress_triggers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('relaxation_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('social_activity_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('learning_interests', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('creative_activities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_daily_habits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_habit_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('plan_satisfaction_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specific_improvements_requested', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['user_assessments.id'], name='plan_customizations_assessment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plan_customizations_pkey')
    )
    op.create_index('ix_plan_customizations_user_id', 'plan_customizations', ['user_id'], unique=False)
    op.create_index('ix_plan_customizations_id', 'plan_customizations', ['id'], unique=False)
    op.create_table('habit_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('habit_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('habit_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('day_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('difficulty_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enjoyment_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('effectiveness_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_taken_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('what_worked_well', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('what_was_challenging', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggestions_for_improvement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('would_repeat', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('energy_level_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_level_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood_after', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='habit_feedback_pkey')
    )
    op.create_index('ix_habit_feedback_user_id', 'habit_feedback', ['user_id'], unique=False)
    op.create_index('ix_habit_feedback_id', 'habit_feedback', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('preferred_wake_up_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_routine_duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exercise_intensity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stress_management_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_morning_activities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_evening_activities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('physical_limitations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_constraints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('environmental_constraints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('primary_wellness_goal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('secondary_goals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('plan_feedback', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_adjustments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_preferences_pkey')
    )
    op.create_index('ix_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    op.create_index('ix_user_preferences_id', 'user_preferences', ['id'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('overall_glow_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('biological_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emotional_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chronological_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['user_assessments.id'], name='progress_snapshots_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='progress_snapshots_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='progress_snapshots_pkey')
    )
    op.create_index('ix_progress_snapshots_user_id', 'progress_snapshots', ['user_id'], unique=False)
    op.create_index('ix_progress_snapshots_id', 'progress_snapshots', ['id'], unique=False)
    op.create_index('ix_progress_snapshots_assessment_id', 'progress_snapshots', ['assessment_id'], unique=False)
    op.create_table('user_assessments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_assessments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('overall_glow_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('biological_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emotional_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chronological_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('glowup_archetype', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('micro_habits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('avatar_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('analysis_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('detailed_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quiz_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_assessments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_assessments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_assessments_user_id', 'user_assessments', ['user_id'], unique=False)
    op.create_index('ix_user_assessments_id', 'user_assessments', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('embedding_vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('topic_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('wellness_domain', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('urgency_level', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('requires_followup', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_timestamp_desc', 'chat_messages', [sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_message_type', 'chat_messages', ['message_type'], unique=False)
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_table('daily_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('plan_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('plan_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['user_assessments.id'], name='daily_plans_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_plans_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_plans_pkey')
    )
    op.create_index('ix_daily_plans_user_id', 'daily_plans', ['user_id'], unique=False)
    op.create_index('ix_daily_plans_id', 'daily_plans', ['id'], unique=False)
    op.create_index('ix_daily_plans_assessment_id', 'daily_plans', ['assessment_id'], unique=False)
    # ### end Alembic commands ###
